### ISSUE TITLE
`order` modifier not working.

### ISSUE THREAD

**Issue by aq1018** [nepalez/query_builder#1]
When using the `#order` modifier, it generates a CQL query like this:

`SELECT * FROM test_keyspace.notifications ORDER BY (user_id DESC)`

But this generates syntax error in CQL 3.3 as it does not expecting `ORDER BY user_id DESC` instead.

**Comment by nepalez** [comment]
Fixed in `v0.0.4`

**Comment by nepalez** [comment]
Thank you!
